version: '3'
services:
  db:
    image: postgres:latest
    container_name: postgres.app
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    build: .
    container_name: app.dev
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=postgres.app
      - SMTP_HOST=mailcatcher.app
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    restart: unless-stopped
  mailcatcher:
    restart: on-failure:10
    container_name: mailcatcher.app
    image: dockage/mailcatcher:0.7.1
    ports:
    - "1080:1080"
    - "1025:1025"
